name: Test

on:
  pull_request:
  push:
    branches:
    - master

jobs:

  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Check go.mod
      run: |
        go mod tidy
        if [ ! -z "$(git status --porcelain go.mod)" ]; then
          printf "go.mod has modifications\n"
          git diff go.mod
          exit 1
        fi
        if [ ! -z "$(git status --porcelain go.sum)" ]; then
          printf "go.sum has modifications\n"
          git diff go.sum
          exit 1
        fi
    - name: Lint code
      run: |
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s
        bin/golangci-lint run -v --timeout=5m
    - name: Run tests
      run: go test -race ./...